### ISSUE TITLE
Ошибка fragment manager при использовании hilt

### ISSUE THREAD

**Issue by MaxVese** [nestoleh/BottomSheet-Spinner#1]
Process: com.sergeenko.lookapp, PID: 11662
    java.lang.IllegalStateException: Unexpected context value dagger.hilt.android.internal.managers.ViewComponentManager.FragmentContextWrapper
        at com.nestoleh.bottomsheetspinner.BottomSheetSpinner.getFragmentManager(BottomSheetSpinner.kt:57)
        at com.nestoleh.bottomsheetspinner.BottomSheetSpinner.access$getFragmentManager$p(BottomSheetSpinner.kt:25)
        at com.nestoleh.bottomsheetspinner.BottomSheetSpinner$onClickListener$1.onClick(BottomSheetSpinner.kt:67)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Думаю нужно просто в fragmentManager get() добавить FragmentContextWrapper

**Comment by nestoleh** [comment]
Внес изменения, релиз 0.1.5, попробуйте и отпишитесь пожалуйста.
